package generatedAssertions.es.us.dp1.l6_3_24_25.Petris.match.model;

import es.us.dp1.l6_3_24_25.Petris.match.model.TurnType;
import jakarta.annotation.Generated;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link TurnType} specific assertions - Generated by CustomAssertionGenerator.
 */
@Generated(value="assertj-assertions-generator")
public abstract class AbstractPetrismatchmodelTurnTypeAssert<S extends AbstractPetrismatchmodelTurnTypeAssert<S, A>, A extends TurnType> extends AbstractComparableAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractPetrismatchmodelTurnTypeAssert}</code> to make assertions on actual TurnType.
   * @param actual the TurnType we want to make assertions on.
   */
  protected AbstractPetrismatchmodelTurnTypeAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
