package generatedAssertions.es.us.dp1.l6_3_24_25.Petris.match.model;

import es.us.dp1.l6_3_24_25.Petris.match.model.PetriDish;
import jakarta.annotation.Generated;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link PetriDish} specific assertions - Generated by CustomAssertionGenerator.
 */
@Generated(value="assertj-assertions-generator")
public abstract class AbstractPetrismatchmodelPetriDishAssert<S extends AbstractPetrismatchmodelPetriDishAssert<S, A>, A extends PetriDish> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractPetrismatchmodelPetriDishAssert}</code> to make assertions on actual PetriDish.
   * @param actual the PetriDish we want to make assertions on.
   */
  protected AbstractPetrismatchmodelPetriDishAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual PetriDish's player1Bacteria is equal to the given one.
   * @param player1Bacteria the given player1Bacteria to compare the actual PetriDish's player1Bacteria to.
   * @return this assertion object.
   * @throws AssertionError - if the actual PetriDish's player1Bacteria is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasPlayer1Bacteria(Integer player1Bacteria) {
    // check that actual PetriDish we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting player1Bacteria of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualPlayer1Bacteria = actual.getPlayer1Bacteria();
    if (!Objects.areEqual(actualPlayer1Bacteria, player1Bacteria)) {
      failWithMessage(assertjErrorMessage, actual, player1Bacteria, actualPlayer1Bacteria);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual PetriDish's player2Bacteria is equal to the given one.
   * @param player2Bacteria the given player2Bacteria to compare the actual PetriDish's player2Bacteria to.
   * @return this assertion object.
   * @throws AssertionError - if the actual PetriDish's player2Bacteria is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasPlayer2Bacteria(Integer player2Bacteria) {
    // check that actual PetriDish we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting player2Bacteria of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualPlayer2Bacteria = actual.getPlayer2Bacteria();
    if (!Objects.areEqual(actualPlayer2Bacteria, player2Bacteria)) {
      failWithMessage(assertjErrorMessage, actual, player2Bacteria, actualPlayer2Bacteria);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
