package generatedAssertions.es.us.dp1.l6_3_24_25.Petris.match.model;

import es.us.dp1.l6_3_24_25.Petris.match.model.Match;
import es.us.dp1.l6_3_24_25.Petris.match.model.PetriDish;
import es.us.dp1.l6_3_24_25.Petris.match.model.TurnType;
import jakarta.annotation.Generated;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.internal.Iterables;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link Match} specific assertions - Generated by CustomAssertionGenerator.
 */
@Generated(value="assertj-assertions-generator")
public abstract class AbstractPetrismatchmodelMatchAssert<S extends AbstractPetrismatchmodelMatchAssert<S, A>, A extends Match> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractPetrismatchmodelMatchAssert}</code> to make assertions on actual Match.
   * @param actual the Match we want to make assertions on.
   */
  protected AbstractPetrismatchmodelMatchAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual Match's boardState contains the given PetriDish elements.
   * @param boardState the given elements that should be contained in actual Match's boardState.
   * @return this assertion object.
   * @throws AssertionError if the actual Match's boardState does not contain all given PetriDish elements.
   */
  public S hasBoardState(PetriDish... boardState) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // check that given PetriDish varargs is not null.
    if (boardState == null) failWithMessage("Expecting boardState parameter not to be null.");

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getBoardState(), boardState);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's boardState contains the given PetriDish elements in Collection.
   * @param boardState the given elements that should be contained in actual Match's boardState.
   * @return this assertion object.
   * @throws AssertionError if the actual Match's boardState does not contain all given PetriDish elements.
   */
  public S hasBoardState(java.util.Collection<? extends PetriDish> boardState) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // check that given PetriDish collection is not null.
    if (boardState == null) {
      failWithMessage("Expecting boardState parameter not to be null.");
      return myself; // to fool Eclipse "Null pointer access" warning on toArray.
    }

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, actual.getBoardState(), boardState.toArray());

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's boardState contains <b>only</b> the given PetriDish elements and nothing else in whatever order.
   * @param boardState the given elements that should be contained in actual Match's boardState.
   * @return this assertion object.
   * @throws AssertionError if the actual Match's boardState does not contain all given PetriDish elements.
   */
  public S hasOnlyBoardState(PetriDish... boardState) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // check that given PetriDish varargs is not null.
    if (boardState == null) failWithMessage("Expecting boardState parameter not to be null.");

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getBoardState(), boardState);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's boardState contains <b>only</b> the given PetriDish elements in Collection and nothing else in whatever order.
   * @param boardState the given elements that should be contained in actual Match's boardState.
   * @return this assertion object.
   * @throws AssertionError if the actual Match's boardState does not contain all given PetriDish elements.
   */
  public S hasOnlyBoardState(java.util.Collection<? extends PetriDish> boardState) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // check that given PetriDish collection is not null.
    if (boardState == null) {
      failWithMessage("Expecting boardState parameter not to be null.");
      return myself; // to fool Eclipse "Null pointer access" warning on toArray.
    }

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, actual.getBoardState(), boardState.toArray());

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's boardState does not contain the given PetriDish elements.
   *
   * @param boardState the given elements that should not be in actual Match's boardState.
   * @return this assertion object.
   * @throws AssertionError if the actual Match's boardState contains any given PetriDish elements.
   */
  public S doesNotHaveBoardState(PetriDish... boardState) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // check that given PetriDish varargs is not null.
    if (boardState == null) failWithMessage("Expecting boardState parameter not to be null.");

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getBoardState(), boardState);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's boardState does not contain the given PetriDish elements in Collection.
   *
   * @param boardState the given elements that should not be in actual Match's boardState.
   * @return this assertion object.
   * @throws AssertionError if the actual Match's boardState contains any given PetriDish elements.
   */
  public S doesNotHaveBoardState(java.util.Collection<? extends PetriDish> boardState) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // check that given PetriDish collection is not null.
    if (boardState == null) {
      failWithMessage("Expecting boardState parameter not to be null.");
      return myself; // to fool Eclipse "Null pointer access" warning on toArray.
    }

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, actual.getBoardState(), boardState.toArray());

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match has no boardState.
   * @return this assertion object.
   * @throws AssertionError if the actual Match's boardState is not empty.
   */
  public S hasNoBoardState() {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have boardState but had :\n  <%s>";

    // check
    if (actual.getBoardState().iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual, actual.getBoardState());
    }

    // return the current assertion for method chaining
    return myself;
  }


  /**
   * Verifies that the actual Match's code is equal to the given one.
   * @param code the given code to compare the actual Match's code to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's code is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasCode(String code) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting code of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualCode = actual.getCode();
    if (!Objects.areEqual(actualCode, code)) {
      failWithMessage(assertjErrorMessage, actual, code, actualCode);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's createdAt is equal to the given one.
   * @param createdAt the given createdAt to compare the actual Match's createdAt to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's createdAt is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasCreatedAt(java.time.LocalDateTime createdAt) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting createdAt of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    java.time.LocalDateTime actualCreatedAt = actual.getCreatedAt();
    if (!Objects.areEqual(actualCreatedAt, createdAt)) {
      failWithMessage(assertjErrorMessage, actual, createdAt, actualCreatedAt);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's creator is equal to the given one.
   * @param creator the given creator to compare the actual Match's creator to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's creator is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasCreator(es.us.dp1.l6_3_24_25.Petris.player.model.Player creator) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting creator of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    es.us.dp1.l6_3_24_25.Petris.player.model.Player actualCreator = actual.getCreator();
    if (!Objects.areEqual(actualCreator, creator)) {
      failWithMessage(assertjErrorMessage, actual, creator, actualCreator);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's endedAt is equal to the given one.
   * @param endedAt the given endedAt to compare the actual Match's endedAt to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's endedAt is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasEndedAt(java.time.LocalDateTime endedAt) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting endedAt of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    java.time.LocalDateTime actualEndedAt = actual.getEndedAt();
    if (!Objects.areEqual(actualEndedAt, endedAt)) {
      failWithMessage(assertjErrorMessage, actual, endedAt, actualEndedAt);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's player1 is equal to the given one.
   * @param player1 the given player1 to compare the actual Match's player1 to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's player1 is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasPlayer1(es.us.dp1.l6_3_24_25.Petris.player.model.Player player1) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting player1 of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    es.us.dp1.l6_3_24_25.Petris.player.model.Player actualPlayer1 = actual.getPlayer1();
    if (!Objects.areEqual(actualPlayer1, player1)) {
      failWithMessage(assertjErrorMessage, actual, player1, actualPlayer1);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's player1Score is equal to the given one.
   * @param player1Score the given player1Score to compare the actual Match's player1Score to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's player1Score is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasPlayer1Score(Integer player1Score) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting player1Score of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualPlayer1Score = actual.getPlayer1Score();
    if (!Objects.areEqual(actualPlayer1Score, player1Score)) {
      failWithMessage(assertjErrorMessage, actual, player1Score, actualPlayer1Score);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's player2 is equal to the given one.
   * @param player2 the given player2 to compare the actual Match's player2 to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's player2 is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasPlayer2(es.us.dp1.l6_3_24_25.Petris.player.model.Player player2) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting player2 of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    es.us.dp1.l6_3_24_25.Petris.player.model.Player actualPlayer2 = actual.getPlayer2();
    if (!Objects.areEqual(actualPlayer2, player2)) {
      failWithMessage(assertjErrorMessage, actual, player2, actualPlayer2);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's player2Score is equal to the given one.
   * @param player2Score the given player2Score to compare the actual Match's player2Score to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's player2Score is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasPlayer2Score(Integer player2Score) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting player2Score of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualPlayer2Score = actual.getPlayer2Score();
    if (!Objects.areEqual(actualPlayer2Score, player2Score)) {
      failWithMessage(assertjErrorMessage, actual, player2Score, actualPlayer2Score);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's startedAt is equal to the given one.
   * @param startedAt the given startedAt to compare the actual Match's startedAt to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's startedAt is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasStartedAt(java.time.LocalDateTime startedAt) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting startedAt of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    java.time.LocalDateTime actualStartedAt = actual.getStartedAt();
    if (!Objects.areEqual(actualStartedAt, startedAt)) {
      failWithMessage(assertjErrorMessage, actual, startedAt, actualStartedAt);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's turn is equal to the given one.
   * @param turn the given turn to compare the actual Match's turn to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's turn is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasTurn(Integer turn) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting turn of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualTurn = actual.getTurn();
    if (!Objects.areEqual(actualTurn, turn)) {
      failWithMessage(assertjErrorMessage, actual, turn, actualTurn);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's turnType is equal to the given one.
   * @param turnType the given turnType to compare the actual Match's turnType to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's turnType is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasTurnType(TurnType turnType) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting turnType of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    TurnType actualTurnType = actual.getTurnType();
    if (!Objects.areEqual(actualTurnType, turnType)) {
      failWithMessage(assertjErrorMessage, actual, turnType, actualTurnType);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Match's winner is equal to the given one.
   * @param winner the given winner to compare the actual Match's winner to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Match's winner is not equal to the given one.
   */
  @SuppressWarnings("deprecation")
  public S hasWinner(Integer winner) {
    // check that actual Match we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting winner of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualWinner = actual.getWinner();
    if (!Objects.areEqual(actualWinner, winner)) {
      failWithMessage(assertjErrorMessage, actual, winner, actualWinner);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
