package generatedAssertions.es.us.dp1.l6_3_24_25.Petris.match.model;

import es.us.dp1.l6_3_24_25.Petris.match.model.Match;
import jakarta.annotation.Generated;

/**
 * {@link Match} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPetrismatchmodelMatchAssert} instead.
 */
@Generated(value="assertj-assertions-generator")
public class PetrismatchmodelMatchAssert extends AbstractPetrismatchmodelMatchAssert<PetrismatchmodelMatchAssert, Match> {

  /**
   * Creates a new <code>{@link PetrismatchmodelMatchAssert}</code> to make assertions on actual Match.
   * @param actual the Match we want to make assertions on.
   */
  public PetrismatchmodelMatchAssert(Match actual) {
    super(actual, PetrismatchmodelMatchAssert.class);
  }

  /**
   * An entry point for PetrismatchmodelMatchAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myMatch)</code> and get specific assertion with code completion.
   * @param actual the Match we want to make assertions on.
   * @return a new <code>{@link PetrismatchmodelMatchAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PetrismatchmodelMatchAssert assertThat(Match actual) {
    return new PetrismatchmodelMatchAssert(actual);
  }
}
