package generatedAssertions.es.us.dp1.l6_3_24_25.Petris.match.model;

import es.us.dp1.l6_3_24_25.Petris.match.model.PetriDish;
import jakarta.annotation.Generated;

/**
 * {@link PetriDish} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPetrismatchmodelPetriDishAssert} instead.
 */
@Generated(value="assertj-assertions-generator")
public class PetrismatchmodelPetriDishAssert extends AbstractPetrismatchmodelPetriDishAssert<PetrismatchmodelPetriDishAssert, PetriDish> {

  /**
   * Creates a new <code>{@link PetrismatchmodelPetriDishAssert}</code> to make assertions on actual PetriDish.
   * @param actual the PetriDish we want to make assertions on.
   */
  public PetrismatchmodelPetriDishAssert(PetriDish actual) {
    super(actual, PetrismatchmodelPetriDishAssert.class);
  }

  /**
   * An entry point for PetrismatchmodelPetriDishAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPetriDish)</code> and get specific assertion with code completion.
   * @param actual the PetriDish we want to make assertions on.
   * @return a new <code>{@link PetrismatchmodelPetriDishAssert}</code>
   */
  @SuppressWarnings("deprecation")
  @org.assertj.core.util.CheckReturnValue
  public static PetrismatchmodelPetriDishAssert assertThat(PetriDish actual) {
    return new PetrismatchmodelPetriDishAssert(actual);
  }
}
