package generatedAssertions.es.us.dp1.l6_3_24_25.Petris.match.model;

import es.us.dp1.l6_3_24_25.Petris.match.model.TurnType;
import jakarta.annotation.Generated;

/**
 * {@link TurnType} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPetrismatchmodelTurnTypeAssert} instead.
 */
@Generated(value="assertj-assertions-generator")
public class PetrismatchmodelTurnTypeAssert extends AbstractPetrismatchmodelTurnTypeAssert<PetrismatchmodelTurnTypeAssert, TurnType> {

  /**
   * Creates a new <code>{@link PetrismatchmodelTurnTypeAssert}</code> to make assertions on actual TurnType.
   * @param actual the TurnType we want to make assertions on.
   */
  public PetrismatchmodelTurnTypeAssert(TurnType actual) {
    super(actual, PetrismatchmodelTurnTypeAssert.class);
  }

  /**
   * An entry point for PetrismatchmodelTurnTypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTurnType)</code> and get specific assertion with code completion.
   * @param actual the TurnType we want to make assertions on.
   * @return a new <code>{@link PetrismatchmodelTurnTypeAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PetrismatchmodelTurnTypeAssert assertThat(TurnType actual) {
    return new PetrismatchmodelTurnTypeAssert(actual);
  }
}
