name: Sincronizar con Repo Público

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push a repositorio público
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'Yabarta'
          destination-repository-name: 'dp1-2025-2026-l6-3-25-public'
          user-email: 'perezsornipablo@gmail.com'
          user-name: 'Pablo Perez Sorni'
          target-branch: main 
